# Configuración del Data Downloader
active_exchange: "bybit"

exchanges:
  bybit:
    enabled: true
    api_key: "your_api_key_here"
    secret: "your_secret_here"
    timeframe: "1h"
    start_date: "2024-01-01"
    end_date: "2024-03-31"
  okx:
    enabled: false
    api_key: "your_api_key_here"
    secret: "your_secret_here"
    timeframe: "1d"
    start_date: "2024-01-01"
    end_date: "2024-03-31"
  kraken:
    enabled: false
    api_key: "your_api_key_here"
    secret: "your_secret_here"
    timeframe: "1d"
    start_date: "2024-01-01"
    end_date: "2024-03-31"
  kucoin:
    enabled: false
    api_key: "your_api_key_here"
    secret: "your_secret_here"
    timeframe: "4h"
    start_date: "2024-01-01"
    end_date: "2024-03-31"

default_symbols:
  - "BTC/USDT"
  - "XRP/USDT"
  - "ADA/USDT"
  - "SOL/USDT"

data_types:
  - "ohlcv"
  - "trades"

max_retries: 3
retry_delay: 5

log_level: "INFO"
log_file: "data_downloader.log"

storage:
  path: "data"
  csv:
    enabled: true
  sqlite:
    enabled: true

normalization:
  enabled: true
  method: "minmax"

indicators:
  volatility:
    enabled: true
    period: 14
    method: "standard_deviation"
  
  heiken_ashi:
    enabled: true
    trend_period: 3
    size_comparison_threshold: 1.2
  
  atr:
    enabled: true
    period: 14
  
  adx:
    enabled: true
    period: 14
    threshold: 25
  
  ema:
    enabled: true
    periods: [10, 20, 200]
  
  parabolic_sar:
    enabled: true
    acceleration: 0.02
    maximum: 0.2